### ISSUE TITLE
Uncaught TypeError: _.merge is not a function

### ISSUE THREAD

**Issue by Tantumonium** [pods-framework/pods-visualize#19]
I know this code is old, but, I just recently discovered Pods, I'm working my way through setting relationship diagrams, and ran across the very interesting sounding... **pods-visualize** via the **Pods PodCast #002**: [Data Structure Planning](https://pods.io/2015/03/13/data-structure-planning-important/)

Anyway, after downloading, installing, and activating this plug-in... when I go to Pods Admin > Pods Visualize... I see a blank page with nothing but "Pods Visualize" displayed.

The console error I'm seeing is as follows:
```
http://dev.beckatl.com/wp-content/plugins/pods-visualize-master/includes/jointjs/joint.min.js?ver=4.9.4
Uncaught TypeError: _.merge is not a function
    at J.c.constructor (joint.min.js?ver=4.9.4:1)
    at J.c [as constructor] (joint.min.js?ver=4.9.4:1)
    at J.c [as constructor] (joint.min.js?ver=4.9.4:1)
    at new J.c (joint.min.js?ver=4.9.4:1)
    at Object.pods_visualize.render (pods-visualize.js?ver=1.0.0:2)
    at HTMLDocument.<anonymous> (pods-visualize.js?ver=1.0.0:1)
    at l (joint.min.js?ver=4.9.4:1)
    at Object.fireWith [as resolveWith] (joint.min.js?ver=4.9.4:1)
    at Function.ready (joint.min.js?ver=4.9.4:1)
    at HTMLDocument.nb (joint.min.js?ver=4.9.4:1)
```

**Comment by pglewis** [comment]
Sorry this flew under the radar for so long, this plugin doesn't have much adoption so I'm guilty of not checking in on this repo often enough.  I'll get to the bottom of this.

**Comment by Tantumonium** [comment]
I'll never complain about something someone is doing for me for free. :) 

Thanks for fixing it. It works perfectly and looks great (and as useful as I was hoping).

**Comment by pglewis** [comment]
There could be a few other oddball things to iron out.  Some of my Pods are showing up without the Pod name label on them on my local install for example.  I'll take a quick poke around.  

This was definitely a "scratch your own itch" project, I wanted something like this for myself.  Definitely in the "useful but very prototype-y" category.
